// <auto-generated />
namespace wtime.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class richiesta_datafine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(richiesta_datafine));
        
        string IMigrationMetadata.Id
        {
            get { return "201706290643030_richiesta_datafine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
